apiVersion: v1
kind: Service
metadata:
  name: distributor
  namespace: pluto
  labels:
    app: distributor
spec:
  type: NodePort
  selector:
    app: distributor
  ports:
  - name: public
    port: 1993
    targetPort: 1993
