apiVersion: v1
kind: Service
metadata:
  name: worker-2
  namespace: pluto
  labels:
    app: worker-2
spec:
  type: LoadBalancer
  selector:
    app: worker-2
  ports:
  - name: mail
    port: 20001
    targetPort: 20001
  - name: sync
    port: 30001
    targetPort: 30001
