apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus.yml
  namespace: prometheus
data:
  prometheus.yml: |
    # https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml
    global:
      scrape_interval: 15s
    scrape_configs:

    # - job_name: 'prometheus'
    #   scrape_interval: 15s
    #   static_configs:
    #   - targets:
    #     - localhost:9090
    #     labels:
    #       app: 'prometheus'

    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

    - job_name: 'kubernetes-services'
      metrics_path: /probe
      params:
        module: [http_2xx]
      kubernetes_sd_configs:
      - role: service
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
        action: keep
        regex: true
      # - source_labels: [__address__]
      #   target_label: __param_target
      # - target_label: __address__
      #   replacement: blackbox
      # - source_labels: [__param_target]
      #   target_label: instance
      # - action: labelmap
      #   regex: __meta_kubernetes_service_label_(.+)
      # - source_labels: [__meta_kubernetes_namespace]
      #   target_label: kubernetes_namespace
      # - source_labels: [__meta_kubernetes_service_name]
      #   target_label: kubernetes_name

    # - job_name: 'kubernetes-pods'
    #   kubernetes_sd_configs:
    #   - role: pod
    #   relabel_configs:
    #   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    #     action: keep
    #     regex: true
    #   - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    #     action: replace
    #     target_label: __metrics_path__
    #     regex: (.+)
    #   - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    #     action: replace
    #     regex: ([^:]+)(?::\d+)?;(\d+)
    #     replacement: $1:$2
    #     target_label: __address__
    #   - action: labelmap
    #     regex: __meta_kubernetes_pod_label_(.+)
    #   - source_labels: [__meta_kubernetes_namespace]
    #     action: replace
    #     target_label: kubernetes_namespace
    #   - source_labels: [__meta_kubernetes_pod_name]
    #     action: replace
    #     target_label: kubernetes_pod_name
