kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-data
  namespace: prometheus
  annotations:
    volume.beta.kubernetes.io/storage-class: ssd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
