apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-03.passwd
  namespace: dovecot-dsync
data:
  passwd: |+
    user2@example.com:{plain}hello123::::
    user5@example.com:{plain}hello123::::
    user8@example.com:{plain}hello123::::
    user11@example.com:{plain}hello123::::
    user14@example.com:{plain}hello123::::
    user17@example.com:{plain}hello123::::
    user20@example.com:{plain}hello123::::
    user23@example.com:{plain}hello123::::
    user26@example.com:{plain}hello123::::
    user29@example.com:{plain}hello123::::
    user32@example.com:{plain}hello123::::
    user35@example.com:{plain}hello123::::
    user38@example.com:{plain}hello123::::
    user41@example.com:{plain}hello123::::
    user44@example.com:{plain}hello123::::
    user47@example.com:{plain}hello123::::
    user50@example.com:{plain}hello123::::
    user53@example.com:{plain}hello123::::
    user56@example.com:{plain}hello123::::
    user59@example.com:{plain}hello123::::
    user62@example.com:{plain}hello123::::
    user65@example.com:{plain}hello123::::
    user68@example.com:{plain}hello123::::
    user71@example.com:{plain}hello123::::
    user74@example.com:{plain}hello123::::
    user77@example.com:{plain}hello123::::
    user80@example.com:{plain}hello123::::
    user83@example.com:{plain}hello123::::
    user86@example.com:{plain}hello123::::
    user89@example.com:{plain}hello123::::
    user92@example.com:{plain}hello123::::
    user95@example.com:{plain}hello123::::
    user98@example.com:{plain}hello123::::
    user101@example.com:{plain}hello123::::
    user104@example.com:{plain}hello123::::
    user107@example.com:{plain}hello123::::
    user110@example.com:{plain}hello123::::
    user113@example.com:{plain}hello123::::
    user116@example.com:{plain}hello123::::
    user119@example.com:{plain}hello123::::
