apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-02.passwd
  namespace: dovecot-dsync
data:
  passwd: |+
    user1@example.com:{plain}hello123::::
    user4@example.com:{plain}hello123::::
    user7@example.com:{plain}hello123::::
    user10@example.com:{plain}hello123::::
    user13@example.com:{plain}hello123::::
    user16@example.com:{plain}hello123::::
    user19@example.com:{plain}hello123::::
    user22@example.com:{plain}hello123::::
    user25@example.com:{plain}hello123::::
    user28@example.com:{plain}hello123::::
    user31@example.com:{plain}hello123::::
    user34@example.com:{plain}hello123::::
    user37@example.com:{plain}hello123::::
    user40@example.com:{plain}hello123::::
    user43@example.com:{plain}hello123::::
    user46@example.com:{plain}hello123::::
    user49@example.com:{plain}hello123::::
    user52@example.com:{plain}hello123::::
    user55@example.com:{plain}hello123::::
    user58@example.com:{plain}hello123::::
    user61@example.com:{plain}hello123::::
    user64@example.com:{plain}hello123::::
    user67@example.com:{plain}hello123::::
    user70@example.com:{plain}hello123::::
    user73@example.com:{plain}hello123::::
    user76@example.com:{plain}hello123::::
    user79@example.com:{plain}hello123::::
    user82@example.com:{plain}hello123::::
    user85@example.com:{plain}hello123::::
    user88@example.com:{plain}hello123::::
    user91@example.com:{plain}hello123::::
    user94@example.com:{plain}hello123::::
    user97@example.com:{plain}hello123::::
    user100@example.com:{plain}hello123::::
    user103@example.com:{plain}hello123::::
    user106@example.com:{plain}hello123::::
    user109@example.com:{plain}hello123::::
    user112@example.com:{plain}hello123::::
    user115@example.com:{plain}hello123::::
    user118@example.com:{plain}hello123::::
