apiVersion: v1
kind: ConfigMap
metadata:
  name: dovecot-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    # This is an example config file

    [server]
    addr = "proxy.dovecot-simple.federation.svc.europe-west1.federation.go-pluto.de:993"
    TLS = true # unused

    [settings]
    threads = 90
    sessions = 600
    throttle = 50 # unused
    seed = 523432432751235809

    [session]
    minlength = 15
    maxlength = 30
