apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-1-eu
  namespace: dovecot-dsync
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-1-eu
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: backend-1-eu
        image: gopluto/dovecot:16.04
        imagePullPolicy: Always
        ports:
        - name: imap
          containerPort: 993
        - name: admin
          containerPort: 12345
        resources:
          requests:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: backend-config
          mountPath: /config
        - name: backend-users
          mountPath: /users
        - name: root-cert
          mountPath: /certs/root/
        - name: eu-cert
          mountPath: /certs/internal/cert/
        - name: eu-key
          mountPath: /certs/internal/key/
      - name: maildir-exporter
        image: gopluto/maildir_exporter
        imagePullPolicy: Always
        command:
        - '/bin/maildir_exporter'
        - '-logLevel'
        - 'debug'
        - '-maildirRootPath'
        - '/data/maildir'
        ports:
        - name: metrics
          containerPort: 9275
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backend1-data
      - name: backend-config
        configMap:
          name: backend-1.conf
      - name: backend-users
        configMap:
          name: users.passwd
      - name: root-cert
        secret:
          secretName: dovecotca.pem
      - name: eu-cert
        secret:
          secretName: eu1.crt
      - name: eu-key
        secret:
          secretName: eu1.key
