apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-1
  namespace: dovecot-simple
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-1
    spec:
      containers:
      - name: backend
        image: gopluto/dovecot
        ports:
        - containerPort: 993
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: maildir
          mountPath: /data/maildir
        - name: backend-config
          mountPath: /config
        - name: backend-users
          mountPath: /users
      volumes:
      - name: maildir
        persistentVolumeClaim:
          claimName: backend1-data
      - name: backend-config
        configMap:
          name: backend.conf
      - name: backend-users
        configMap:
          name: users.passwd
