apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: dovecot-simple
  labels:
    app: proxy
spec:
  type: LoadBalancer
  ports:
  - port: 993
  selector:
    app: proxy
  clusterIP: 10.31.248.1
