apiVersion: v1
kind: ConfigMap
metadata:
  name: pluto-us-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    [server]
    addr = "104.196.4.142:1993"
    TLS = true # unused

    [settings]
    threads = 1
    sessions = 5000
    throttle = 50 # unused
    seed = 4

    [session]
    minlength = 15
    maxlength = 40
