kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: europe-west1-b-ssd
  namespace: pluto
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: europe-west1-b
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: europe-west2-b-ssd
  namespace: pluto
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: europe-west2-b
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: us-east1-b-ssd
  namespace: pluto
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: us-east1-b
