apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-2-eu
  namespace: dovecot-dsync
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-2-eu
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: backend-2-eu
        image: gopluto/dovecot:16.04
        imagePullPolicy: Always
        ports:
        - name: imap
          containerPort: 993
        - name: admin
          containerPort: 12345
        resources:
          requests:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: backend-config
          mountPath: /config
        - name: backend-users
          mountPath: /users
        - name: root-cert
          mountPath: /certs/root/
        - name: eu-cert
          mountPath: /certs/internal/cert/
        - name: eu-key
          mountPath: /certs/internal/key/
      - name: maildir-exporter
        image: gopluto/maildir_exporter:du
        imagePullPolicy: Always
        command:
        - '/bin/maildir_exporter'
        - '-logLevel'
        - 'error'
        - '-maildirRootPath'
        - '/data/maildir'
        - '-interval'
        - '1s'
        - '-users'
        - 'user58@example.com,user76@example.com'
        - '-workerName'
        - 'backend-02-eu'
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: pluto-167312
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /certs/accounts/service-account.json
        ports:
        - name: metrics
          containerPort: 9275
        volumeMounts:
        - name: data
          mountPath: /data
        - name: serviceaccount
          mountPath: /certs/accounts
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backend2-data
      - name: backend-config
        configMap:
          name: backend-2.conf
      - name: backend-users
        configMap:
          name: backend-02.passwd
      - name: root-cert
        secret:
          secretName: dovecotca.pem
      - name: eu-cert
        secret:
          secretName: eu2.crt
      - name: eu-key
        secret:
          secretName: eu2.key
      - name: serviceaccount
        secret:
          secretName: service-account.json
