apiVersion: v1
kind: Service
metadata:
  name: backend-2-eu
  namespace: dovecot-dsync
  labels:
    app: backend-2-eu
spec:
  type: LoadBalancer
  ports:
  - name: imap
    port: 993
    targetPort: 993
  - name: admin
    port: 12345
    targetPort: 12345
  selector:
    app: backend-2-eu
  clusterIP: 10.31.249.101
