apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-2
  namespace: dovecot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-2
    spec:
      containers:
      - name: backend
        image: gopluto/dovecot
        ports:
        - containerPort: 993
        resources:
          requests:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: glusterfsvol
          mountPath: /mnt/glusterfs
        - name: backend-config
          mountPath: /config
        - name: backend-users
          mountPath: /users
      volumes:
      - name: glusterfsvol
        glusterfs:
          endpoints: gluster-cluster
          path: volume1
          readOnly: false
      - name: backend-config
        configMap:
          name: backend.conf
      - name: backend-users
        configMap:
          name: users.passwd
