apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-3-us
  namespace: dovecot-dsync
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-3-us
    spec:
      containers:
      - name: backend-3-us
        image: gopluto/dovecot
        ports:
        - name: imap
          containerPort: 993
        - name: admin
          containerPort: 12345
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: maildir
          mountPath: /data/maildir
        - name: backend-config
          mountPath: /config
        - name: backend-users
          mountPath: /users
      volumes:
      - name: maildir
        persistentVolumeClaim:
          claimName: backend3-data
      - name: backend-config
        configMap:
          name: backend-3.conf
      - name: backend-users
        configMap:
          name: users.passwd
