apiVersion: v1
kind: Service
metadata:
  name: backend-3-us
  namespace: dovecot-dsync
  labels:
    app: backend-3-us
spec:
  type: LoadBalancer
  ports:
  - port: 993
  - port: 12345
  selector:
    app: backend-3-us
  clusterIP: 10.15.245.102
