apiVersion: v1
kind: ConfigMap
metadata:
  name: dsync-dovecot-eu-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    [server]
    addr = "104.155.49.100:993"
    TLS = true # unused

    [settings]
    threads = 90
    sessions = 5000
    throttle = 50 # unused
    seed = 1

    [session]
    minlength = 15
    maxlength = 40
