apiVersion: v1
kind: ConfigMap
metadata:
  name: dsync-dovecot-eu-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    [server]
    addr = "proxy.dovecot-dsync.federation.svc.europe-west1.federation.go-pluto.de:993"
    TLS = true # unused

    [settings]
    threads = 20
    sessions = 5000
    throttle = 50 # unused
    seed = 1

    [session]
    minlength = 15
    maxlength = 40
