apiVersion: v1
kind: Service  
metadata:
  name: backend-1-us
  namespace: dovecot-dsync
  labels:
    app: backend-1-us
spec:
  type: LoadBalancer
  ports:
  - name: imap
    port: 993
    targetPort: 993
  - name: admin
    port: 12345
    targetPort: 12345
  selector:
    app: backend-1-us
  clusterIP: 10.15.245.100
