apiVersion: v1
kind: ConfigMap
metadata:
  name: dsync-dovecot-us-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    # This is an example config file

    [server]
    addr = "35.196.197.212:993"
    TLS = true # unused

    [settings]
    threads = 90
    sessions = 600
    throttle = 50 # unused
    seed = 123432432751135809

    [session]
    minlength = 15
    maxlength = 30
