apiVersion: v1
kind: ConfigMap
metadata:
  name: dsync-dovecot-us-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    [server]
    # addr = "proxy.dovecot-dsync.federation.svc.us-east1-b.us-east1.federation.go-pluto.de:993"
    addr = "35.196.197.212:993"
    TLS = true # unused

    [settings]
    threads = 20
    sessions = 5000
    throttle = 50 # unused
    seed = 1

    [session]
    minlength = 15
    maxlength = 40
