kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheus-global
  namespace: monitoring
  annotations:
    federation.kubernetes.io/deployment-preferences: |
        {
            "rebalance": true,
            "clusters": {
                "europe-west3-b": {
                    "minReplicas": 1,
                    "maxReplicas": 1,
                    "weight": 1
                }
            }
        }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-global
  template:
    metadata:
      name: prometheus-global
      labels:
        app: prometheus-global
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v1.7.1
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-global.yml
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-global-data
