kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/probe: '/metrics'
  labels:
    name: prometheus-global
  name: prometheus-global
  namespace: monitoring
spec:
  selector:
    app: prometheus-global
  ports:
  - name: prometheus-global
    protocol: TCP
    port: 9090
