apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
      hostNetwork: true
      hostPID: true
