apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
    name: node-exporter
spec:
  type: ClusterIP
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
