apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage
  namespace: pluto
  annotations:
    federation.kubernetes.io/deployment-preferences: |
        {
            "rebalance": true,
            "clusters": {
                "europe-west1-b": {
                    "minReplicas": 0,
                    "maxReplicas": 0,
                    "weight": 0
                },
                "europe-west2-b": {
                    "minReplicas": 1,
                    "maxReplicas": 1,
                    "weight": 1
                },
                "us-east1-b": {
                    "minReplicas": 0,
                    "maxReplicas": 0,
                    "weight": 0
                }
            }
        }
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: storage
        image: gopluto/pluto
        imagePullPolicy: Always
        command:
        - '/bin/pluto'
        - '-loglevel'
        - 'error'
        - '-config'
        - '/config/pluto.toml'
        - '-storage'
        ports:
        - name: metrics
          containerPort: 9999
        resources:
          requests:
            cpu: 600m
            memory: 10240Mi
        volumeMounts:
        - name: data
          mountPath: /data
        - name: pluto-config
          mountPath: /config
        - name: pluto-users
          mountPath: /users
        - name: root-cert
          mountPath: /certs/root
        - name: internal-storage-cert
          mountPath: /certs/internal/cert/
        - name: internal-storage-key
          mountPath: /certs/internal/key/
      - name: maildir-exporter
        image: gopluto/maildir_exporter:du
        imagePullPolicy: Always
        command:
        - '/bin/maildir_exporter'
        - '-logLevel'
        - 'error'
        - '-maildirRootPath'
        - '/data/maildirs'
        - '-interval'
        - '3s'
        - '-users'
        - 'user9,user27,user58,user76,user95,user113'
        - '-workerName'
        - 'storage'
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: pluto-167312
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /certs/accounts/service-account.json
        ports:
        - name: metrics
          containerPort: 9275
        volumeMounts:
        - name: data
          mountPath: /data
        - name: serviceaccount
          mountPath: /certs/accounts
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: storage-data
      - name: pluto-config
        configMap:
          name: eu-pluto.toml
      - name: pluto-users
        configMap:
          name: users.txt
      - name: root-cert
        secret:
          secretName: root-cert.pem
      - name: internal-storage-cert
        secret:
          secretName: internal-storage-cert.pem
      - name: internal-storage-key
        secret:
          secretName: internal-storage-key.pem
      - name: serviceaccount
        secret:
          secretName: service-account.json
