apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: dovecot-dsync
  labels:
    app: proxy
spec:
  # type: LoadBalancer
  ports:
  - port: 993
  selector:
    app: proxy
  clusterIP: 10.43.243.1
