apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-dovecot-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    # This is an example config file

    [server]
    addr = "proxy.dovecot-simple.svc.cluster.local:993"
    TLS = true # unused

    [settings]
    threads = 90
    sessions = 6000
    throttle = 50 # unused
    seed = 1

    [session]
    minlength = 15
    maxlength = 30
