apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-dovecot-benchmark.conf
  namespace: benchmark
data:
  config.toml: |-
    [server]
    addr = "104.155.50.136:993"
    TLS = true # unused

    [settings]
    threads = 20
    sessions = 1000
    throttle = 50 # unused
    seed = 1

    [session]
    minlength = 15
    maxlength = 40
